[package]
name = "actix_middleware_client"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.40", features = ["macros", "rt-multi-thread"] }
reqwest = { version = "0.12.7", default-features = false, features = ["rustls-tls"] }
