[package]
name = "actix_diesel"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
dotenvy = "0.15.7"
serde = { version = "1.0.219", features = ["derive"] }
diesel = { version = "2.2.4", features = ["sqlite", "r2d2"] }
